worker_processes 1;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    client_max_body_size 10M;

    upstream app {
        server app:3000;
    }

    server {
        listen 80;
        server_name $DOMAIN_NAME;

        # For HTTPS, redirect all HTTP traffic to HTTPS.
        # For HTTP-only, comment out the line below and handle traffic directly in this block.
        location / {
            return 301 https://$host$request_uri;
        }
    }

    # To run without SSL, comment out this entire 'server' block.
    server {
        listen 443 ssl;
        server_name $DOMAIN_NAME;

        # To run without SSL, comment out the following 4 lines.
        ssl_certificate /etc/letsencrypt/live/$DOMAIN_NAME/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/$DOMAIN_NAME/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        location / {
            proxy_pass http://app;
            proxy_set_header Host $host;
            proxy_redirect https://localhost:3000/ /;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
